name: mobil_programlama_odev
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: 0.17.0
  hooks_riverpod: ^0.14.0+4
  auto_route: ^3.2.0
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  supercharged: ^2.0.0
  dio: ^4.0.4
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  shared_preferences: ^2.0.11
  flutter_barcode_scanner: ^2.0.0
  file_picker: ^4.3.0
  firebase_storage: ^10.2.4
  introduction_screen: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  auto_route_generator: ^3.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/svg/